set -g default-terminal "xterm-256color"
set -ga terminal-overrides ',xterm-256color:RGB'

set -sg escape-time 0
set -g mouse on

# Options
set-option -g history-limit 10000

set -g status-position top

# Set prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Shift Alt Vim Keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!" # quick reload

set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'Tecu23/tmux-mountain-theme'

# Session persistence
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Continuum settings
set -g @continuum-restore 'on'  # Auto-restore sessions on tmux start
set -g @continuum-save-interval '15'  # Save every 15 minutes

run '~/.tmux/plugins/tpm/tpm'
